### ISSUE TITLE
Suggested Feature: Global Functions (+ code)

### ISSUE THREAD

**Issue by kevincannon** [MariusRumpf/node-lifx#11]
I think it would be nice to have global functions on the client object, so you can do this:

```
client.allOff();
client.allOn();
client.allColor(55,33,99);
```

I needed this for my experiments, so I wrote some simple wrappers for this. Feel free to add it if it's useful. The error handling is managed well by the light methods.

**in client.js**
```
/**
 * Turns all known bulbs off
 * @return null
 */
Client.prototype.allOff = function(duration) {
  
  _.forEach(this.devices, function(light) {
      light.off(duration);
  });
  return null;
};

/**
 * Turns all known bulbs on
 * @return null
 */
Client.prototype.allOn = function(duration) {

  _.forEach(this.devices, function(light) {
      light.on(duration);
  });
  return null;
};

/**
 * Change hue of all bulbs
 * @return null
 */
Client.prototype.allColor = function(hue, saturation, brightness, kelvin, duration) {

  _.forEach(this.devices, function(light) {
      light.color(hue, saturation, brightness, kelvin, duration);
  });
  return null;
};
```

Also, I created a new commandline helloworld for myself, it's nothing special, but sharing it in case it's useful to you:
http://pastebin.com/tzqnfkdx

**Comment by MariusRumpf** [comment]
Thanks for the suggestion. This will be integrated when I get to groups and locations. 
But I think it makes sense that the `client.lights`  function returns objects of the same type as the `light` function. Then somebody could call something like:
```js
client.lights().forEach(function(light) {
    light.on();
});
```

I will have a look at this soon.

**Comment by kevincannon** [comment]
Looking forward to seeing the groups & locations stuff. Sounds good! :)
