### ISSUE TITLE
"LIFX bulb off method expects duration to be a number"

### ISSUE THREAD

**Issue by ajsaini** [MariusRumpf/node-lifx#13]
When I try running my code, it outputs:

"LIFX bulb off method expects duration to be a number"

I'm relatively new to node js, so I wasn't able to understand why the issue occurred. Any ideas why?

My code is as follows:

var LifxClient = require('node-lifx').Client;
var client = new LifxClient();

client.on('bulb-new', function (bulb) {
	bulb.on(['1000']); 
});

client.init();

**Comment by MariusRumpf** [comment]
Hey ajsaini, 

bulb.on expects a number as parameter. You gave it an array containing a string.

```js
var LifxClient = require('node-lifx').Client;
var client = new LifxClient();

client.on('bulb-new', function (bulb) {
bulb.on(1000); 
});

client.init();
```

**Comment by MariusRumpf** [comment]
I assume this answered your question.
