### ISSUE TITLE
node-lifx on raspberry pi

### ISSUE THREAD

**Issue by NitroOxyde** [MariusRumpf/node-lifx#16]
Hi, 
I'm try to get this librarie working on my raspberry pi 2 (running node.js v0.10.2), but whenever I try to use it or to launch cli.js I get this error:
```
LIFX UDP Packet error
Trace: { [Error : getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
    at Client.<anonymous> (/home/pi/node_modules/node-lifx/lib/lifx/client.js:101:13)
    at Socket.EventEmitter.emit (events.js:95:17)
    at dgram.js:184:12
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:124:7)
LIFX error:
Error: getaddrinfo ENOTFOUND
    at errnoExeption (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```
(Sorry for my english by the way)

**Comment by MariusRumpf** [comment]
I did not test the library with node v0.10, an update might help. I will try to install it on my raspberry pi 2 with iojs-v2.5 and report back.

**Comment by NitroOxyde** [comment]
Ok, thank you !

**Comment by MariusRumpf** [comment]
Just tried it successful on my raspberry pi 2 - model b with debian jessie and iojs-v2.5.0. 
I would consider this a problem with node 0.10., please try a newer version of node >= 0.12 or iojs >= 1.

**Comment by Nibbler999** [comment]
Needs #17 to work on 0.10

**Comment by NitroOxyde** [comment]
It's working ! Thanks a lot !

**Comment by MariusRumpf** [comment]
#17 is part of 0.2.1 release I just published.
