### ISSUE TITLE
Callback for light.on + light.off?

### ISSUE THREAD

**Issue by lukehorvat** [MariusRumpf/node-lifx#20]
Hi. I've started building [a CLI for LIFX bulbs](https://github.com/ssilab/lifx-cli), utilizing your package because it has a nice API. So thanks.

I'm just wondering, would it be possible for `light.on` and `light.off` to have a callback for when the operation completes? Maybe along with a timeout as well? I'm currently using [a polling approach](https://github.com/ssilab/lifx-cli/blob/c6cb1fc/lib/commands/power-off.js#L13-L27), but it's a bit messy.

**Comment by MariusRumpf** [comment]
Hi, cool to hear about your cli project. The LIFX protocol supports to send a confirmation package when requested in header (`ackRequired`). I have not come to implement this now #14 . 
If you wanna give it a try you could have a look at the fork https://github.com/WigWagCo/node-lifx which did some work already, didn't check it myself.
