### ISSUE TITLE
Socket error after bind fails

### ISSUE THREAD

**Issue by dpjanes** [MariusRumpf/node-lifx#24]
In `node-lifx/lib/lifx/client.js` if `bind` fails (say, because the address is in use) the error is emitted correctly. Unfortunately, later on `socket.send` will cause an exception during scanning because `self.port` is not set up correctly.

This can be fixed by moving this code

    // Start scanning
    if (opts.startDiscovery) {
      this.startDiscovery();
    }

Inside the `this.socket.bind` block that immediately precedes it. e.g.

      this.socket.bind(opts.port, opts.address, function() {
        this.socket.setBroadcast(true);
        this.emit('listening');
        this.port = opts.port;
        if (typeof callback === 'function') {
          return callback();
        }

        // Start scanning
        if (opts.startDiscovery) {
          this.startDiscovery();
        }
      }.bind(this));

**Comment by MariusRumpf** [comment]
Moving the start of scanning would solve this issue only part wise (if you do not use startDiscovery directly afterwards) . Say you use the `startDiscovery` and `stopDiscovery` methods directly then the error would still be thrown. We should integrate a check if the socket is bound to fix this.

**Comment by MariusRumpf** [comment]
Moving the start of scanning would also be correct in order of sending start. Should all be solved now and be part of the next release, thanks.
