### ISSUE TITLE
color: rgb hex enhancement.

### ISSUE THREAD

**Issue by roccomuso** [MariusRumpf/node-lifx#28]
wouldn't be useful to improve the <code>.color</code> method to make the use of RGB hex possible?

**Comment by MariusRumpf** [comment]
There is also a rgbw method provided by the LIFX lights. That might also be a nice thing.

**Comment by roccomuso** [comment]
I didn't found it on their documentation (can you link it to me?). I might work on this ;)

**Comment by MariusRumpf** [comment]
It is undocumented but I found parts of it in the old ruby-gem from LIFX and it is used in the app as well.
https://github.com/LIFX/lifx-gem/search?utf8=%E2%9C%93&q=rgbw

**Comment by roccomuso** [comment]
I saw that: https://github.com/MariusRumpf/node-lifx/blob/master/lib/lifx/packets/setRgbw.js
I'm writing a new method to use that kind of packet. Nothing else is using it right? Did you forget about it?

**Comment by MariusRumpf** [comment]
Oh, didn't know I had worked on that before, it is not used as far as I know.

That is correct, you can pass RGB to the api, there was a post on how they convert it in the forums recently. https://community.lifx.com/t/how-to-convert-rgb-into-hsbk/1270/2

**Comment by MariusRumpf** [comment]
Started working on the basics since I didn't hear of any progress.

**Comment by roccomuso** [comment]
@MariusRumpf Sorry, quite busy in the last few months.. Are you planning to use the forgotten ***setRgbw.js*** ? :)

**Comment by MariusRumpf** [comment]
@roccomuso No problem, no I used the hsbk methods still. I have added methods to convert rgb to hsb.

**Comment by MariusRumpf** [comment]
This was part of the 0.7.0 release with `colorRgb` and `colorRgbHex`.
