### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by msimp19** [MariusRumpf/node-lifx#39]
How would I be able to import this with ES6 syntax, seeing as by default you are supposed to use a ```require``` statement like so:

```
var LifxClient = require('node-lifx').Client;
var client = new LifxClient();

client.init();
```

How would you do this with ES6 syntax?

**Comment by MariusRumpf** [comment]
ES6 import syntax can only be used with transpiling for now and is not native so far.
I would think something like this might work (not tested):
```javascript
import {Client as LifxClient} from 'node-lifx';
const client = new LifxClient;

client.init();
```

Does this work for you?

**Comment by msimp19** [comment]
I'm pretty sure the second way worked for me. Thanks!
