### ISSUE TITLE
Implement infrared color packets to control LIFX+

### ISSUE THREAD

**Issue by MariusRumpf** [MariusRumpf/node-lifx#40]
The new LIFX+ lamp does use a different message to set it's "color" since it uses infrared light. These message have to be implemented to control these. Documentation can be found [here](https://lan.developer.lifx.com/v2.0/docs/light-messages#section-getinfrared-120).

**Comment by ristomatti** [comment]
@MariusRumpf I would like try to help with this and also #41. I have pre-ordered both LIFX Z  and LIFX+ but my experience with protocol level communication is limited and I would probably need some support or pointers along the way.

My only experience is from last week, trying to understand the inner workings of node-lifx to improve its performance when sending commands to multiple lights. With trial, error and luck I found two distinct ways to do that. I'm planning on creating separate pull requests on these (it might take a while before I find time to do that though). In case I get that far - would the pull requests be sufficient or should I also create issues to link them to?

**Comment by MariusRumpf** [comment]
Yeah, feel free to do so and add pull requests then, no separate issues needed. Maybe I should add a gitter chat so you we can talk when needed.

**Comment by ristomatti** [comment]
That would be really helpful especially when I get the new devices and need to try and make sense of the protocol specification. But I also have some questions about architectural decisions related to the performance improvements. Would it be to contact you through email?

**Comment by MariusRumpf** [comment]
[https://gitter.im/node-lifx/Lobby]()

**Comment by MariusRumpf** [comment]
Thanks for all the work, this is now part of the 0.8.0 release.
