### ISSUE TITLE
powerOn or powerOff with duration set to 0 is not instant

### ISSUE THREAD

**Issue by steve2507** [MariusRumpf/node-lifx#44]
When I use the on() or off() methods on a bulb with a duration set to 0, than the light still seems to fade in/out over ~100-200ms.
Funny enough, when I set the brightness to 0 with a duration of 0, than it *is* instant.

I'm not sure if this is a 'problem' with this npm module or with the LIFX firmware itself. Any ideas?

**Comment by MariusRumpf** [comment]
You can observe the same problem when using the microphone effect from the LIFX Android App. The sound ist not in sync with the sound and there is a noticeable delay. People tried syncing to music and there they have the same problem with different libraries too. This library passes the delay directly to the light. With all these facts I consider this to be a firmware problem.

**Comment by steve2507** [comment]
As I already expected. Thanks for the info!
