### ISSUE TITLE
Constant disconnecting

### ISSUE THREAD

**Issue by KiwiAs** [MariusRumpf/node-lifx#47]
Hey mate, im having issues with bulbs constantly going on and offline. I did try messing with config.json and changing lightOfflineTolerance=15 and resendMaxTimes= 6 
Which resulted in a slight improvement. The lifx app controls them fine even when they are "offline" in homebridge. Any ideas? Really stumped.

**Comment by KiwiAs** [comment]
I did check with the homebridge-lifx group but they referred me here.

**Comment by MariusRumpf** [comment]
Hey, 
the library is sending discovery packets to each light every 5 seconds. The lights report back to the library that they are there if they receive this packet. This constant on and offline switching means a light did not answer for multiple request. lightOfflineTolerance sets the limits how often the light is allowed to not report back before being reported disconnected. In your case with a value of 15 the light is reported as offline if it hasn't answered for 75 seconds, default is 15 seconds.
Now the question is, why do your lights not report back. I do not have insights on how the LIFX app does do it, I can only use the ways specified in the [lan protcol](https://lan.developer.lifx.com/).
